Hoang signup feature
th1590/JobFinder-portal pull request #16
Opened 2021-06-02 15:00 UTC by th1590

2021-06-02 15:00 UTC, th1590 commented
@nguyentrinhan-dev  review đê

2021-06-02 15:02 UTC, nguyentrinhan-dev approved these changes

2021-06-02 15:02 UTC, nguyentrinhan-dev commented on src/page/Signup.jsx
> +}
newline in EOF convention
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2021-06-02 15:03 UTC, nguyentrinhan-dev requested changes

2021-06-02 15:03 UTC, nguyen-tri-nhan commented on src/page/Signup.jsx
> +}
newline in EOF convention
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2021-06-03 10:31 UTC, nguyentrinhan-dev approved these changes

2021-06-03 10:32 UTC, merged